export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCESS = "FETCH_PRODUCTS_SUCESS";
export const FETCH_PRODUCTS_SUCESS_LOADMORE = "FETCH_PRODUCTS_SUCESS_LOADMORE";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_INFO = "GET_PRODUCT_INFO";
export const GET_PRODUCT_INFO_ALWAYS = "GET_PRODUCT_INFO_ALWAYS";
export const ADD_BUTTON_CART = "ADD_BUTTON_CART";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_COMPLETE_PURCHASE = "DELETE_COMPLETE_PURCHASE";
export const FETCH_JOBS = "FETCH_JOBS";
export const FETCH_JOBS_SUCESS = "FETCH_JOBS_SUCESS";
export const FETCH_JOBS_FAIL = "FETCH_JOBS_FAIL";
export const GET_JOBINFO = "GET_JOBINFO";
export const GET_URL_JOB = "GET_URL_JOB";
export const GET_PRODUCT_NAME_STORE = "GET_PRODUCT_NAME_STORE";
export const KEYWORD_SEARCH_JOB = "KEYWORD_SEARCH_JOB";
export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const FILTER_PRODUCT_SUCCESS = "FILTER_PRODUCT_SUCCESS";
export const FILTER_JOB = "FILTER_JOB";
export const FILTER_JOB_SUCCESS = "FILTER_JOB_SUCCESS";

export const STATUS_CODE = {
    SUCESS : 200,
    CREATED : 201,
    UPDATE : 202,
};

